-- Remover tabelas existentes com restrições em cascata
DROP TABLE ADDRESS CASCADE CONSTRAINTS;

DROP TABLE BOO CASCADE CONSTRAINTS;

DROP TABLE BOO_OPERATION CASCADE CONSTRAINTS;

DROP TABLE CLIENT CASCADE CONSTRAINTS;

DROP TABLE CLIENTTYPE CASCADE CONSTRAINTS;

DROP TABLE COMPONENT CASCADE CONSTRAINTS;

DROP TABLE COUNTRY CASCADE CONSTRAINTS;

DROP TABLE EXTERNALPARTS CASCADE CONSTRAINTS;

DROP TABLE INTERMEDIATEPRODUCT CASCADE CONSTRAINTS;

DROP TABLE INTERNALPART CASCADE CONSTRAINTS;

DROP TABLE OPERATION CASCADE CONSTRAINTS;

DROP TABLE OPERATIONTYPE CASCADE CONSTRAINTS;

DROP TABLE "Order" CASCADE CONSTRAINTS;

DROP TABLE ORDERPRODUCT CASCADE CONSTRAINTS;

DROP TABLE PART CASCADE CONSTRAINTS;

DROP TABLE PARTIN CASCADE CONSTRAINTS;

DROP TABLE PARTOUT CASCADE CONSTRAINTS;

DROP TABLE PLACEDORDER CASCADE CONSTRAINTS;

DROP TABLE PRODUCT CASCADE CONSTRAINTS;

DROP TABLE PRODUCTFAMILY CASCADE CONSTRAINTS;

DROP TABLE PRODUCTIONORDER CASCADE CONSTRAINTS;

DROP TABLE RAWMATERIAL CASCADE CONSTRAINTS;

DROP TABLE SUPPLIER CASCADE CONSTRAINTS;

DROP TABLE UNIT CASCADE CONSTRAINTS;

DROP TABLE WORKSTATIONS CASCADE CONSTRAINTS;

DROP TABLE WORKSTATIONTYPES CASCADE CONSTRAINTS;

DROP TABLE WSTYPES_OPERATIONTYPES CASCADE CONSTRAINTS;

-- Criação das tabelas
CREATE TABLE ADDRESS (
  ADDRESS VARCHAR2(255) NOT NULL,
  ZIP VARCHAR2(8) NOT NULL,
  TOWN VARCHAR2(255) NOT NULL,
  COUNTRYCODE VARCHAR2(2) NOT NULL,
  CLIENTNIF VARCHAR2(15) NOT NULL,
  PRIMARY KEY (ADDRESS, ZIP)
);

CREATE TABLE BOO (
  BOOID VARCHAR2(4) NOT NULL,
  PARTID VARCHAR2(50) NOT NULL,
  PRIMARY KEY (BOOID)
);

CREATE TABLE BOO_OPERATION (
  OPID NUMBER(10) NOT NULL,
  BOOID VARCHAR2(4) NOT NULL,
  NEXTOPID NUMBER(10),
  PRIMARY KEY (OPID, BOOID)
);

CREATE TABLE CLIENT (
  NIF VARCHAR2(15) NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  EMAIL VARCHAR2(255) NOT NULL,
  PHONE NUMBER(10) NOT NULL,
  IDCLIENT NUMBER(10) NOT NULL,
  CID VARCHAR2(2) NOT NULL,
  STATUS NUMBER(1) DEFAULT 1 NOT NULL,
  PRIMARY KEY (NIF)
);

CREATE TABLE CLIENTTYPE (
  CID VARCHAR2(2) NOT NULL,
  TYPE VARCHAR2(50) NOT NULL,
  PRIMARY KEY (CID)
);

CREATE TABLE COMPONENT (
  PARTID VARCHAR2(50) NOT NULL,
  PRIMARY KEY (PARTID)
);

CREATE TABLE COUNTRY (
  COUNTRYCODE VARCHAR2(2) NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  PRIMARY KEY (COUNTRYCODE)
);

CREATE TABLE EXTERNALPARTS (
  PARTID VARCHAR2(50) NOT NULL,
  STOCK NUMBER(10) NOT NULL,
  PRIMARY KEY (PARTID)
);

CREATE TABLE INTERMEDIATEPRODUCT (
  PARTID VARCHAR2(50) NOT NULL,
  PRIMARY KEY (PARTID)
);

CREATE TABLE INTERNALPART (
  PARTID VARCHAR2(50) NOT NULL,
  PRIMARY KEY (PARTID)
);

CREATE TABLE OPERATION (
  OPID NUMBER(10),
  NAME VARCHAR2(255) NOT NULL,
  OPERATIONTYPEOTID NUMBER(10) NOT NULL,
  EXPECTEDEXECUTIONTIME NUMBER(10) NOT NULL,
  PRIMARY KEY (OPID)
);

CREATE TABLE OPERATIONTYPE (
  OTID NUMBER(10),
  DESCRIPTION VARCHAR2(255) NOT NULL,
  PRIMARY KEY (OTID)
);

CREATE TABLE "Order" (
  OID NUMBER(10),
  DATEDELIVERY DATE NOT NULL,
  DATEORDER DATE NOT NULL,
  CLIENTNIF VARCHAR2(15) NOT NULL,
  PRIMARY KEY (OID)
);

CREATE TABLE ORDERPRODUCT (
  QUANTITY NUMBER(10) NOT NULL,
  OID NUMBER(10) NOT NULL,
  PRODUCTPARTID VARCHAR2(50) NOT NULL,
  PRIMARY KEY (OID, PRODUCTPARTID)
);

CREATE TABLE PART (
  PARTID VARCHAR2(50) NOT NULL,
  DESCRIPTION VARCHAR2(255) NOT NULL,
  PRIMARY KEY (PARTID)
);

CREATE TABLE PARTIN (
  QUANTITYIN NUMBER(10) NOT NULL,
  OPID NUMBER(10) NOT NULL,
  BOOID VARCHAR2(4) NOT NULL,
  PARTID VARCHAR2(50) NOT NULL,
  PRIMARY KEY (OPID, BOOID, PARTID)
);

CREATE TABLE PARTOUT (
  QUANTITY NUMBER(10) NOT NULL,
  PARTID VARCHAR2(50) NOT NULL,
  OPID NUMBER(10) NOT NULL,
  BOOID VARCHAR2(4) NOT NULL,
  PRIMARY KEY (PARTID, OPID, BOOID)
);

CREATE TABLE PLACEDORDER (
  PARTID VARCHAR2(50) NOT NULL,
  SUPPLIERID NUMBER(10) NOT NULL,
  QUANTITY NUMBER(10) NOT NULL,
  UNITCOST NUMBER(10) NOT NULL,
  DATESTART DATE NOT NULL,
  DATEEND DATE,
  MINIMUMORDERSIZE NUMBER(10) NOT NULL,
  PRIMARY KEY (PARTID, SUPPLIERID)
);

CREATE TABLE PRODUCT (
  NAME VARCHAR2(255) NOT NULL,
  PFID NUMBER(3) NOT NULL,
  PARTID VARCHAR2(50) NOT NULL,
  PRIMARY KEY (PARTID)
);

CREATE TABLE PRODUCTFAMILY (
  PFID NUMBER(3),
  NAME VARCHAR2(50) NOT NULL,
  PRIMARY KEY (PFID)
);

CREATE TABLE PRODUCTIONORDER (
  PRORID VARCHAR2(10) NOT NULL,
  OID NUMBER(10) NOT NULL,
  PRODUCTPARTID VARCHAR2(50) NOT NULL,
  PRIMARY KEY (PRORID)
);

CREATE TABLE RAWMATERIAL (
  PARTID VARCHAR2(50) NOT NULL,
  UNITID NUMBER(4) NOT NULL,
  PRIMARY KEY (PARTID)
);

CREATE TABLE SUPPLIER (
  SUPPLIERID NUMBER(10),
  NAME VARCHAR2(255) NOT NULL,
  PRIMARY KEY (SUPPLIERID)
);

CREATE TABLE UNIT (
  UNITID NUMBER(4),
  NAME VARCHAR2(255) NOT NULL,
  PRIMARY KEY (UNITID)
);

CREATE TABLE WORKSTATIONS (
  WSID NUMBER(4),
  NAME VARCHAR2(50) NOT NULL,
  DESCRIPTION VARCHAR2(255) NOT NULL,
  WTID VARCHAR2(5) NOT NULL,
  PRIMARY KEY (WSID)
);

CREATE TABLE WORKSTATIONTYPES (
  WTID VARCHAR2(5) NOT NULL,
  NAME VARCHAR2(255) NOT NULL,
  MAXIMUMEXECUTIONTIME NUMBER(10) NOT NULL,
  SETUPTIME NUMBER(10) NOT NULL,
  PRIMARY KEY (WTID)
);

CREATE TABLE WSTYPES_OPERATIONTYPES (
  WTID VARCHAR2(5) NOT NULL,
  OPERATIONTYPEOTID NUMBER(10) NOT NULL,
  PRIMARY KEY (WTID, OPERATIONTYPEOTID)
);

-- Adição das restrições de chave estrangeira
ALTER TABLE WORKSTATIONS
  ADD CONSTRAINT FKWORKSTATIO342984 FOREIGN KEY (
    WTID
  )
    REFERENCES WORKSTATIONTYPES (
      WTID
    );

ALTER TABLE "Order"
  ADD CONSTRAINT FKORDER455373 FOREIGN KEY (
    CLIENTNIF
  )
    REFERENCES CLIENT (
      NIF
    );

ALTER TABLE CLIENT
  ADD CONSTRAINT FKCLIENT207010 FOREIGN KEY (
    CID
  )
    REFERENCES CLIENTTYPE (
      CID
    );

ALTER TABLE ORDERPRODUCT
  ADD CONSTRAINT FKORDERPRODU492632 FOREIGN KEY (
    OID
  )
    REFERENCES "Order" (
      OID
    );

ALTER TABLE ORDERPRODUCT
  ADD CONSTRAINT FKORDERPRODU415970 FOREIGN KEY (
    PRODUCTPARTID
  )
    REFERENCES PRODUCT (
      PARTID
    );

ALTER TABLE PRODUCT
  ADD CONSTRAINT FKPRODUCT436806 FOREIGN KEY (
    PFID
  )
    REFERENCES PRODUCTFAMILY (
      PFID
    );

ALTER TABLE BOO_OPERATION
  ADD CONSTRAINT FKBOO_OPERAT961240 FOREIGN KEY (
    OPID
  )
    REFERENCES OPERATION (
      OPID
    );

ALTER TABLE BOO_OPERATION
  ADD CONSTRAINT FKBOO_OPERAT227172 FOREIGN KEY (
    BOOID
  )
    REFERENCES BOO (
      BOOID
    );

ALTER TABLE PRODUCTIONORDER
  ADD CONSTRAINT FKPRODUCTION804538 FOREIGN KEY (
    OID,
    PRODUCTPARTID
  )
    REFERENCES ORDERPRODUCT (
      OID,
      PRODUCTPARTID
    );

ALTER TABLE WSTYPES_OPERATIONTYPES
  ADD CONSTRAINT FKWSTYPES_OP693016 FOREIGN KEY (
    WTID
  )
    REFERENCES WORKSTATIONTYPES (
      WTID
    );

ALTER TABLE ADDRESS
  ADD CONSTRAINT FKADDRESS919413 FOREIGN KEY (
    COUNTRYCODE
  )
    REFERENCES COUNTRY (
      COUNTRYCODE
    );

ALTER TABLE ADDRESS
  ADD CONSTRAINT FKADDRESS947374 FOREIGN KEY (
    CLIENTNIF
  )
    REFERENCES CLIENT (
      NIF
    );

ALTER TABLE OPERATION
  ADD CONSTRAINT FKOPERATION437580 FOREIGN KEY (
    OPERATIONTYPEOTID
  )
    REFERENCES OPERATIONTYPE (
      OTID
    );

ALTER TABLE WSTYPES_OPERATIONTYPES
  ADD CONSTRAINT FKWSTYPES_OP385854 FOREIGN KEY (
    OPERATIONTYPEOTID
  )
    REFERENCES OPERATIONTYPE (
      OTID
    );

ALTER TABLE EXTERNALPARTS
  ADD CONSTRAINT FKEXTERNALPA66507 FOREIGN KEY (
    PARTID
  )
    REFERENCES PART (
      PARTID
    );

ALTER TABLE COMPONENT
  ADD CONSTRAINT FKCOMPONENT647854 FOREIGN KEY (
    PARTID
  )
    REFERENCES EXTERNALPARTS (
      PARTID
    );

ALTER TABLE RAWMATERIAL
  ADD CONSTRAINT FKRAWMATERIA486501 FOREIGN KEY (
    PARTID
  )
    REFERENCES EXTERNALPARTS (
      PARTID
    );

ALTER TABLE INTERNALPART
  ADD CONSTRAINT FKINTERNALPA593933 FOREIGN KEY (
    PARTID
  )
    REFERENCES PART (
      PARTID
    );

ALTER TABLE PRODUCT
  ADD CONSTRAINT FKPRODUCT294354 FOREIGN KEY (
    PARTID
  )
    REFERENCES INTERNALPART (
      PARTID
    );

ALTER TABLE INTERMEDIATEPRODUCT
  ADD CONSTRAINT FKINTERMEDIA298766 FOREIGN KEY (
    PARTID
  )
    REFERENCES INTERNALPART (
      PARTID
    );

ALTER TABLE BOO
  ADD CONSTRAINT FKBOO179738 FOREIGN KEY (
    PARTID
  )
    REFERENCES INTERNALPART (
      PARTID
    );

ALTER TABLE PARTOUT
  ADD CONSTRAINT FKPARTOUT809562 FOREIGN KEY (
    PARTID
  )
    REFERENCES INTERNALPART (
      PARTID
    );

ALTER TABLE PLACEDORDER
  ADD CONSTRAINT FKPLACEDORDE158230 FOREIGN KEY (
    PARTID
  )
    REFERENCES EXTERNALPARTS (
      PARTID
    );

ALTER TABLE PLACEDORDER
  ADD CONSTRAINT FKPLACEDORDE171431 FOREIGN KEY (
    SUPPLIERID
  )
    REFERENCES SUPPLIER (
      SUPPLIERID
    );

ALTER TABLE RAWMATERIAL
  ADD CONSTRAINT FKRAWMATERIA187550 FOREIGN KEY (
    UNITID
  )
    REFERENCES UNIT (
      UNITID
    );

ALTER TABLE BOO_OPERATION
  ADD CONSTRAINT FKBOO_OPERAT215277 FOREIGN KEY (
    NEXTOPID
  )
    REFERENCES OPERATION (
      OPID
    );

ALTER TABLE PARTOUT
  ADD CONSTRAINT FKPARTOUT249189 FOREIGN KEY (
    OPID,
    BOOID
  )
    REFERENCES BOO_OPERATION (
      OPID,
      BOOID
    );

ALTER TABLE PARTIN
  ADD CONSTRAINT FKPARTIN518976 FOREIGN KEY (
    OPID,
    BOOID
  )
    REFERENCES BOO_OPERATION (
      OPID,
      BOOID
    );

ALTER TABLE PARTIN
  ADD CONSTRAINT FKPARTIN959241 FOREIGN KEY (
    PARTID
  )
    REFERENCES EXTERNALPARTS (
      PARTID
    );

-- A declaração problemática foi removida:
-- ALTER TABLE PartIN ADD CONSTRAINT FKPartIN152758 FOREIGN KEY () REFERENCES BOO_Operation ();